config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: :all
  devise_scope :user do
    get 'users/sign_in' => 'users/sessions#new', as: 'new_user_session'
    post 'users/sign_in' => 'users/sessions#create', as: 'user_session'
    delete 'users/sign_out' => 'users/sessions#destroy', as: 'destroy_user_session'
    get 'users/sign_up' => 'users/registrations#new', as: 'new_user_registration'
    post 'users/sign_up' => 'users/registrations#create', as: 'user_registration'
    get 'users/password/new' => 'users/passwords#new', as: 'new_user_password'
    post 'users/password' => 'users/passwords#create', as: 'user_password'
    get 'users/password/edit' => 'users/passwords#edit', as: 'edit_user_password'
    put 'users/password' => 'users/passwords#update', as: ''
    get 'users/invitation/accept' => 'users/invitations#edit', as: 'accept_user_invitation'
    get 'users/invitation/new' => 'users/invitations#new', as: 'new_user_invitation'
    put 'users/invitation/new' => 'users/invitations#update', as: ''
    post 'users/invitation/new' => 'users/invitations#create', as: 'user_invitation'
  end

  devise_for :admins, skip: :all
  devise_scope :admin do
    get 'admins/sign_in' => 'admins/sessions#new', as: 'new_admin_session'
    post 'admins/sign_in' => 'admins/sessions#create', as: 'admin_session'
    delete 'admins/sign_out' => 'admins/sessions#destroy', as: 'destroy_admin_session'
    get 'admins/sign_up' => 'admins/registrations#new', as: 'new_admin_registration'
    post 'admins/sign_up' => 'admins/registrations#create', as: 'admin_registration'
    get 'admins/password/new' => 'admins/passwords#new', as: 'new_admin_password'
    post 'admins/password' => 'admins/passwords#create', as: 'admin_password'
    get 'admins/password/edit' => 'admins/passwords#edit', as: 'edit_admin_password'
    put 'admins/password' => 'admins/passwords#update', as: ''
  end
  # 共通
  root 'home#top'
  get 'about' => 'home#about', as: 'about'
  get 'signup/select' => 'home#signup_select', as: 'signup_select'
  get 'login/select' => 'home#login_select', as: 'login_select'
  get 'rooms/check' => 'rooms#check', as: 'check'
  resources :inquiries, only: [:create] do
    collection do
      post :confirm
    end
  end
  # get 'inquiries/confirm' => 'home#top', as: '/'
  # 管理者
  namespace :admins do
    resources :rooms, only: [:new, :create, :edit, :update]
    get 'top' => 'home#top', as: 'top'
    resources :children, only: [:index, :show]
    resources :contacts, only: [:new, :create, :index, :show] do
      collection do
        post :confirm
      end
    end
    get 'room_access' => 'children#room_access', as: 'room_access'
    put 'room_access/enter' => 'children#enter', as: 'enter'
    put 'room_access/leave' => 'children#leave', as: 'leave'
    get 'room_access/mail' => 'children#mail', as: 'room_access_children_mail'
    get 'room_access/mail_all' => 'children#mail_all', as: 'room_access_mail_all'
    resources :users, only: [:show, :index, :destroy]
    resources :admins, only: [:show, :edit, :update]
    get '/confirm' => 'admins#confirm', as: 'confirm'
    put '/:id/hide' => 'admins#hide', as: 'hide'
    resources :plans, only: [:show, :index]
    resources :groups
    resources :events
    resources :albums
  end
  # ユーザー
  namespace :users do
    get 'top' => 'home#top', as: 'top'
    resources :children
    # post 'children/new' => 'children#create', as: 'new_child'
    # patch 'users/:id/edit' => 'users#update', as: 'edit_user'
    resources :users
    get '/confirm' => 'users#confirm', as: 'confirm'
    put '/:id/hide' => 'users#hide', as: 'hide'
    resources :contacts, only: [:index, :show] do
      member do
        get :read
      end
    end
    resources :plans, only: [:new, :index, :create, :update]
    resources :events do
      resources :event_attendances
    end
    resources :albums
  end
end

app/views/search/_albums.html.slim
a.btn.btn_theme_main data-target="#modal1" data-toggle="modal" type="button"
    i.fas.fa-search
        | 検索
#modal1.modal.fade aria-hidden="true" aria-labelledby="label1" role="dialog" tabindex="-1"
     .modal-dialog role="document"
      .modal-content
        .modal-header
            button.close aria-label="Close" data-dismiss="modal" type="button"
                span aria-hidden="true"  ×
            h3#label1.modal-title アルバム検索
        .modal-body
                = search_form_for q, url: admins_albums_path do |f|
                            .search
                                .field
                                    = f.label :name, 'アルバム名で検索',class:"form__label"
                                    = f.collection_select :name_cont,Album.where(room_id: @room.id),:name, :name, { include_blank: '選択してください'},{class:"form__item_input"}

                            .search
                                -#タグが重複しないようにラジオボタン で一覧表示
                                .field.check__box
                                    = f.label :name, 'タグで検索',class:"form__label"
                                    = f.collection_check_boxes :tags_name_eq_any, Tag.where(q.id).select(:name).distinct, :name, :name

                                .action
                                    = f.submit '検索',class:"form__btn"

app/views/search/_children.html.slim
a.btn.btn_theme_main data-target="#modal1" data-toggle="modal" type="button"
    i.fas.fa-search
        | 検索
#modal1.modal.fade aria-hidden="true" aria-labelledby="label1" role="dialog" tabindex="-1"
     .modal-dialog role="document"
      .modal-content
        .modal-header
            button.close aria-label="Close" data-dismiss="modal" type="button"
                span aria-hidden="true"  ×
            h3#label1.modal-title 児童検索
        .modal-body
                = search_form_for q, url: admins_children_path do |f|
                            .search
                                .field
                                    = f.label :first_name, '児童検索(名前）',class:"form__label"
                                    = f.search_field :first_name_or_last_name_or_first_name_kana_or_last_name_kana_cont,class:"form__item_input"
                                .field
                                    = f.label :first_name, '児童検索(クラス）',class:"form__label"
                                    = f.search_field :school_class_cont,class:"form__item_input"
                                .field
                                    = f.label :gender, '性別',class:"form__label"
                                    = f.select :gender_eq, [['男', 1], ['女', 2], ['その他', 3]], { include_blank: '選択してください'},{class: "form__item_select"}
                                .field
                                    = f.label :grade, '学年',class:"form__label"
                                    = f.select :grade_eq, [['年少', 1], ['年中', 2], ['年長', 3], ['1年', 4], ['2年', 5], ['3年', 6], ['4年', 7], ['5年', 8], ['6年', 9]], { include_blank: '選択してください'}, {class: "form__item_select"}
                                .action
                                    = f.submit '検索',class:"form__btn"

app/views/search/_contacts.html.slim
a.btn.btn_theme_main data-target="#modal1" data-toggle="modal" type="button"
    i.fas.fa-search
        | 検索
#modal1.modal.fade aria-hidden="true" aria-labelledby="label1" role="dialog" tabindex="-1"
     .modal-dialog role="document"
      .modal-content
        .modal-header
            button.close aria-label="Close" data-dismiss="modal" type="button"
                span aria-hidden="true"  ×
            h3#label1.modal-title 連絡網検索
        .modal-body
                = search_form_for q, url: admins_contacts_path do |f|
                            .search
                                .field
                                    = f.label :subject, 'キーワード検索',class:"form__label"
                                    = f.search_field :subject_or_text_cont,class:"form__item_input"
                                .field
                                    = f.label :subject, '日付検索',class:"form__label"
                                    = f.date_field :created_at_gteq,class:"form__item_input_s"
                                    = f.date_field :created_at_lteq_end_of_day,class:"form__item_input_s"
                                    /end_of_dayで時間部分関係なく範囲検索できる(ransack.rbにconfig記載)
                                .action
                                    = f.submit '検索',class:"form__btn"

app/views/search/_plans.html.slim
a.btn.btn_theme_main data-target="#modal1" data-toggle="modal" type="button"
    i.fas.fa-search
        | 検索
#modal1.modal.fade aria-hidden="true" aria-labelledby="label1" role="dialog" tabindex="-1"
     .modal-dialog role="document"
      .modal-content
        .modal-header
            button.close aria-label="Close" data-dismiss="modal" type="button"
                span aria-hidden="true"  ×
            h3#label1.modal-title 児童検索
        .modal-body
                = search_form_for q, url: admins_plans_path do |f|
                            .search
                                .field
                                    = f.label :first_name, '児童検索(名前）',class:"form__label"
                                    = f.search_field :first_name_or_last_name_or_first_name_kana_or_last_name_kana_cont,class:"form__item_input"
                                .field
                                    = f.label :first_name, '児童検索(クラス）',class:"form__label"
                                    = f.search_field :school_class_cont,class:"form__item_input"
                                .field
                                    = f.label :gender, '性別',class:"form__label"
                                    = f.select :gender_eq, [['男', 1], ['女', 2], ['その他', 3]], { include_blank: '選択してください'},{class: "form__item_select"}
                                .field
                                    = f.label :grade, '学年',class:"form__label"
                                    = f.select :grade_eq, [['年少', 1], ['年中', 2], ['年長', 3], ['1年', 4], ['2年', 5], ['3年', 6], ['4年', 7], ['5年', 8], ['6年', 9]], { include_blank: '選択してください'}, {class: "form__item_select"}
                                .action
                                    = f.submit '検索',class:"form__btn"

app/views/search/_room_accesses.html.slim
a.btn.btn_theme_main data-target="#modal1" data-toggle="modal" type="button"
    i.fas.fa-search
        | 検索
#modal1.modal.fade aria-hidden="true" aria-labelledby="label1" role="dialog" tabindex="-1"
     .modal-dialog role="document"
      .modal-content
        .modal-header
            button.close aria-label="Close" data-dismiss="modal" type="button"
                span aria-hidden="true"  ×
            h3#label1.modal-title 児童検索
        .modal-body
                = search_form_for q, url: admins_room_access_path do |f|
                            .search
                                .field
                                    = f.label :first_name, '児童検索(名前）',class:"form__label"
                                    = f.search_field :first_name_or_last_name_or_first_name_kana_or_last_name_kana_cont,class:"form__item_input"
                                .field
                                    = f.label :first_name, '児童検索(クラス）',class:"form__label"
                                    = f.search_field :school_class_cont,class:"form__item_input"
                                .field
                                    = f.label :gender, '性別',class:"form__label"
                                    = f.select :gender_eq, [['男', 1], ['女', 2], ['その他', 3]], { include_blank: '選択してください'},{class: "form__item_select"}
                                .field
                                    = f.label :grade, '学年',class:"form__label"
                                    = f.select :grade_eq, [['年少', 1], ['年中', 2], ['年長', 3], ['1年', 4], ['2年', 5], ['3年', 6], ['4年', 7], ['5年', 8], ['6年', 9]], { include_blank: '選択してください'}, {class: "form__item_select"}
                                .field
                                    = f.label :room_access, '入室済み児童',class:"form__label"
                                    = f.radio_button :room_access_eq, " ",{:checked => true}
                                    | 選択しない
                                    = f.radio_button :room_access_eq, true
                                    | 入室
                                .action
                                    = f.submit '検索',class:"form__btn"

app/views/search/_user_albums.html.slim
a.btn.btn_theme_main data-target="#modal1" data-toggle="modal" type="button"
    i.fas.fa-search
        | 検索
#modal1.modal.fade aria-hidden="true" aria-labelledby="label1" role="dialog" tabindex="-1"
     .modal-dialog role="document"
      .modal-content
        .modal-header
            button.close aria-label="Close" data-dismiss="modal" type="button"
                span aria-hidden="true"  ×
            h3#label1.modal-title アルバム検索
        .modal-body
                = search_form_for q, url: users_albums_path do |f|
                            .search
                                .field
                                    = f.label :name, 'アルバム名',class:"form__label"
                                    = f.collection_select :name_cont,Album.where(room_id: @room.id),:name, :name, { include_blank: '選択してください'},{class:"form__item_input"}
                            .search
                                .field.check__box
                                    = f.label :name, 'タグで検索',class:"form__label"
                                    = f.collection_check_boxes :tags_name_eq_any, Tag.where(q.id).select(:name).distinct, :name, :name
                                -#タグが重複しないようにラジオボタン で一覧表示
                                .action
                                    = f.submit '検索',class:"form__btn"

app/views/search/_user_contacts.html.slim
a.btn.btn_theme_main data-target="#modal1" data-toggle="modal" type="button"
    i.fas.fa-search
        | 検索
#modal1.modal.fade aria-hidden="true" aria-labelledby="label1" role="dialog" tabindex="-1"
     .modal-dialog role="document"
      .modal-content
        .modal-header
            button.close aria-label="Close" data-dismiss="modal" type="button"
                span aria-hidden="true"  ×
            h3#label1.modal-title 連絡網検索
        .modal-body
                = search_form_for q, url: users_contacts_path do |f|
                            .search
                                .field
                                    = f.label :subject, 'キーワード検索',class:"form__label"
                                    = f.search_field :subject_or_text_cont,class:"form__item_input"
                                .field
                                    = f.label :subject, '日付検索',class:"form__label"
                                    = f.date_field :created_at_gteq,class:"form__item_input_s"
                                    = f.date_field :created_at_lteq_end_of_day,class:"form__item_input_s"
                                    /end_of_dayで時間部分関係なく範囲検索できる(ransack.rbにconfig記載)
                                .action
                                    = f.submit '検索',class:"form__btn"

app/views/search/_users.html.slim
a.btn.btn_theme_main data-target="#modal1" data-toggle="modal" type="button"
    i.fas.fa-search
        | 検索
#modal1.modal.fade aria-hidden="true" aria-labelledby="label1" role="dialog" tabindex="-1"
     .modal-dialog role="document"
      .modal-content
        .modal-header
            button.close aria-label="Close" data-dismiss="modal" type="button"
                span aria-hidden="true"  ×
            h3#label1.modal-title 会員検索
        .modal-body
                = search_form_for q, url: admins_users_path do |f|
                            .search
                                .field
                                    = f.label :first_name, '会員検索(名前）',class:"form__label"
                                    = f.search_field :first_name_or_last_name_or_first_name_kana_or_last_name_kana_cont,class:"form__item_input"
                                .action
                                    = f.submit '検索',class:"form__btn"