config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: :all
  devise_scope :user do
    get 'users/sign_in' => 'users/sessions#new', as: 'new_user_session'
    post 'users/sign_in' => 'users/sessions#create', as: 'user_session'
    delete 'users/sign_out' => 'users/sessions#destroy', as: 'destroy_user_session'
    get 'users/sign_up' => 'users/registrations#new', as: 'new_user_registration'
    post 'users/sign_up' => 'users/registrations#create', as: 'user_registration'
    get 'users/password/new' => 'users/passwords#new', as: 'new_user_password'
    post 'users/password' => 'users/passwords#create', as: 'user_password'
    get 'users/password/edit' => 'users/passwords#edit', as: 'edit_user_password'
    put 'users/password' => 'users/passwords#update', as: ''
    get 'users/invitation/accept' => 'users/invitations#edit', as: 'accept_user_invitation'
    get 'users/invitation/new' => 'users/invitations#new', as: 'new_user_invitation'
    put 'users/invitation/new' => 'users/invitations#update', as: ''
    post 'users/invitation/new' => 'users/invitations#create', as: 'user_invitation'
  end

  devise_for :admins, skip: :all
  devise_scope :admin do
    get 'admins/sign_in' => 'admins/sessions#new', as: 'new_admin_session'
    post 'admins/sign_in' => 'admins/sessions#create', as: 'admin_session'
    delete 'admins/sign_out' => 'admins/sessions#destroy', as: 'destroy_admin_session'
    get 'admins/sign_up' => 'admins/registrations#new', as: 'new_admin_registration'
    post 'admins/sign_up' => 'admins/registrations#create', as: 'admin_registration'
    get 'admins/password/new' => 'admins/passwords#new', as: 'new_admin_password'
    post 'admins/password' => 'admins/passwords#create', as: 'admin_password'
    get 'admins/password/edit' => 'admins/passwords#edit', as: 'edit_admin_password'
    put 'admins/password' => 'admins/passwords#update', as: ''
  end
  # 共通
  root 'home#top'
  get 'about' => 'home#about', as: 'about'
  get 'signup/select' => 'home#signup_select', as: 'signup_select'
  get 'login/select' => 'home#login_select', as: 'login_select'
  get 'rooms/check' => 'rooms#check', as: 'check'
  resources :inquiries, only: [:create] do
    collection do
      post :confirm
    end
  end
  # get 'inquiries/confirm' => 'home#top', as: '/'
  # 管理者
  namespace :admins do
    resources :rooms, only: [:new, :create, :edit, :update]
    get 'top' => 'home#top', as: 'top'
    resources :children, only: [:index, :show]
    resources :contacts, only: [:new, :create, :index, :show] do
      collection do
        post :confirm
      end
    end
    get 'room_access' => 'children#room_access', as: 'room_access'
    put 'room_access/enter' => 'children#enter', as: 'enter'
    put 'room_access/leave' => 'children#leave', as: 'leave'
    get 'room_access/mail' => 'children#mail', as: 'room_access_children_mail'
    get 'room_access/mail_all' => 'children#mail_all', as: 'room_access_mail_all'
    resources :users, only: [:show, :index, :destroy]
    resources :admins, only: [:show, :edit, :update]
    get '/confirm' => 'admins#confirm', as: 'confirm'
    put '/:id/hide' => 'admins#hide', as: 'hide'
    resources :plans, only: [:show, :index]
    resources :groups
    resources :events
    resources :albums
  end
  # ユーザー
  namespace :users do
    get 'top' => 'home#top', as: 'top'
    resources :children
    # post 'children/new' => 'children#create', as: 'new_child'
    # patch 'users/:id/edit' => 'users#update', as: 'edit_user'
    resources :users
    get '/confirm' => 'users#confirm', as: 'confirm'
    put '/:id/hide' => 'users#hide', as: 'hide'
    resources :contacts, only: [:index, :show] do
      member do
        get :read
      end
    end
    resources :plans, only: [:new, :index, :create, :update]
    resources :events do
      resources :event_attendances
    end
    resources :albums
  end
end

app/controllers/admins/home_controller.rb
class Admins::HomeController < ApplicationController
  before_action :authenticate_admin!
  before_action :room_check
  def top
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
    @inquiry = Inquiry.new
  end

  def about
  end

  def signup_select
  end

  def login_select
  end
end

app/controllers/users/home_controller.rb
class Users::HomeController < ApplicationController
  before_action :authenticate_user!
  before_action :child_check
  def top
  end
end

app/helpers/admins/home_helper.rb
module Admins::HomeHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users/home_helper.rb
module Users::HomeHelper
end

app/views/home/about.html.slim
.container
  .row
    section.about.about__cont
      h2 このサイトについて
      p　
      | このサイトはポートフォリオ作品です。
      br
      | 実際の施設での運用にはご利用いただけませんので、ご注意ください。
      br
      | 管理者がルームを作成し、ルームキーを伝えることで会員を招待できます。
      br
      | 招待された会員はルームキーを入力することで、新規登録が可能になります。
      br
      | ぜひお試しください。
      p　
      h3.text_bold テスト管理者
      p メールアドレス:　test@admin.com
      p パスワード：　111111
      h3.text_bold テスト会員
      p ルームキー: room
      p メールアドレス:　test@user.com
      p パスワード：　111111

app/views/home/login_select.html.slim
.container
  .row
    section.user-select
      .wrap
        h2.user-select__misashi
          | どちらでログインしますか？
        = link_to new_user_session_path, class: "btn user-select__btn btn_color_yellow" do
          i.fas.fa-users.user-select__icon
          p.txtm
            | ユーザーログイン
        = link_to new_admin_session_path, class: "btn user-select__btn btn_color_orange " do
          i.fas.fa-user-cog.user-select__icon
          p.txtm
            | 管理者ログイン

app/views/home/signup_select.html.slim
.container
  .row
    section.user-select
      .wrap
        h2.user-select__misashi
          | どちらで新規登録しますか？
        = link_to check_path, class: "btn user-select__btn btn_color_yellow" do
          i.fas.fa-users.user-select__icon
          p.txtm
            | ユーザー新規登録
        = link_to new_admin_registration_path, class: "btn user-select__btn btn_color_orange " do
          i.fas.fa-user-cog.user-select__icon
          p.txtm
            | 管理者新規登録

app/views/home/top.html.slim
.top_bg
  .container
    .row
      section.main-visual
        .main-visual__cont
          .main-visual_left
            = image_tag asset_path("PC.png"), class: "main-visual__img fadein"
          .main-visual_right
            h2.txt_color_white.main-visual__txt
              | 出欠確認や連絡網をスムーズに
              br
              | 保育へのゆとりを
            .signup_btn
              p.txt_color_yellow.txt_size_m 新規登録ですぐに使用できます
              = link_to "いますぐ新規登録", signup_select_path, class: "btn btn_size_l btn_theme_signup"
.container
  .row
    section.point
      h3.point__heading.fadein.fadein_bottom
        = image_tag asset_path("logo-blue.png"), class: "point__logo"
        | は、保育者の事務業務をICTで省力化し、
        br
        | 保育・教育の質向上を支援するツールです。
      .point__cont.fadein.fadein_bottom
        .point__box
          .point__detail
            p.txt_size_s
            | 習い事など出入りが多く
            br
            | 情報共有がしきれない
          = image_tag asset_path("access.jpg"), class: "point__img"
          p.txt_color_blue.txt_size_l 入退室管理
        .point__box
          .point__detail
            p.txt_size_s
            | 予定表を子どもが出し忘れたり
            br
            | なくしてしまうことが…
          = image_tag asset_path("calender.jpg"), class: "point__img"
          p.txt_color_blue.txt_size_l 予定表管理
        .point__box
          .point__detail
            p.txt_size_s
            | 情報共有や緊急の時
            br
            | 連絡を素早く行いたい
          = image_tag asset_path("contact.jpg"), class: "point__img"
          p.txt_color_blue.txt_size_l 連絡網
        .point__box
          .point__detail
            p.txt_size_s
            | 児童の人数が多く
            br
            | 名簿の作成や管理が大変
          = image_tag asset_path("children.jpg"), class: "point__img"
          p.txt_color_blue.txt_size_l 児童名簿

.top_bg
  .container
    .row
      section.intro
        .intro__box
          .intro__txt_box.fadein.fadein_left
            p.txt_color_blue.intro__count 01
            p.txt_size_l
              span.marker 入退室管理
            p.txt_size_m.font-weight-normal
                | 子どもが登所した際に入室、退室をクリックするだけで切り替えが可能。入室時退室時に保護者へメールを送ることが可能です。
          = image_tag asset_path("enter.jpg"), class: "intro__img"
        .intro__box
            .intro__txt_box.fadein.fadein_right
              p.txt_color_blue.intro__count 02
              p.txt_size_l
                span.marker 予定表管理
              p.txt_size_m
                | フォームから提出された児童ごとの予定表をまとめて確認できます。
                br
                |その日の出欠も表示できます。
            = image_tag asset_path("calender2.jpg"), class: "intro__img"
        .intro__box
            .intro__txt_box.fadein.fadein_left
              p.txt_color_blue.intro__count 03
              p.txt_size_l
                span.marker 連絡網
              p.txt_size_m
                | 日々の連絡を一括で行えます。
                br
                | メールアドレスを全員分登録する手間もなく、施設に属する保護者へ連絡がスムーズに行えます。
                | また、宛先をグループ化し、特定のメンバーにのみ送信も可能です。
            = image_tag asset_path("contact2.jpg"), class: "intro__img"
        .intro__box
            .intro__txt_box.fadein.fadein_right
              p.txt_color_blue.intro__count 04
              p.txt_size_l
                span.marker 児童名簿
              p.txt_size_m
                | 保護者が登録した児童の一覧を表示できます。
                br
                | 表示した一覧は印刷して児童名簿としても使用できます。
            = image_tag asset_path("children2.jpg"), class: "intro__img"
.container
  .row
    section.catch-copy.fadein.fadein_bottom
      h2.catch-copy__heading 体験してみませんか？
      p.txt_size_m 新規登録ですぐに使用できます
      = link_to "いますぐ新規登録", signup_select_path, class: "btn btn_size_l btn_theme_signup"
.top_bg
  .container
    .row
      section.inquiry
        h2.inquiry__txt.txt_color_white お問い合わせ
        .form
          .form__cont
            = form_with model: @inquiry, url: confirm_inquiries_path(@inquiry), local: true do |f|
                = render "layouts/errors", obj: @inquiry
                .field
                  .form__label
                    span.form__item 必須
                    = f.label :name
                  = f.text_field :name, class: "form__item_input", placeholder: "例）山田太郎"
                .field
                  .form__label
                    span.form__item 必須
                    = f.label :phone_number
                  = f.text_field :phone_number, class:"form__item_input", placeholder: "例）1110001"
                .field
                  .form__label
                    span.form__item 必須
                    = f.label :email
                  = f.text_field :email, class:"form__item_input", placeholder: "例）example@gmail.com"
                .field
                  .form__label
                    span.form__item 必須
                    = f.label :message
                  = f.text_area :message, class:"form__item_textarea"
                .actions
                  = f.submit "確認画面へ", class:"form__btn"