config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: :all
  devise_scope :user do
    get 'users/sign_in' => 'users/sessions#new', as: 'new_user_session'
    post 'users/sign_in' => 'users/sessions#create', as: 'user_session'
    delete 'users/sign_out' => 'users/sessions#destroy', as: 'destroy_user_session'
    get 'users/sign_up' => 'users/registrations#new', as: 'new_user_registration'
    post 'users/sign_up' => 'users/registrations#create', as: 'user_registration'
    get 'users/password/new' => 'users/passwords#new', as: 'new_user_password'
    post 'users/password' => 'users/passwords#create', as: 'user_password'
    get 'users/password/edit' => 'users/passwords#edit', as: 'edit_user_password'
    put 'users/password' => 'users/passwords#update', as: ''
    get 'users/invitation/accept' => 'users/invitations#edit', as: 'accept_user_invitation'
    get 'users/invitation/new' => 'users/invitations#new', as: 'new_user_invitation'
    put 'users/invitation/new' => 'users/invitations#update', as: ''
    post 'users/invitation/new' => 'users/invitations#create', as: 'user_invitation'
  end

  devise_for :admins, skip: :all
  devise_scope :admin do
    get 'admins/sign_in' => 'admins/sessions#new', as: 'new_admin_session'
    post 'admins/sign_in' => 'admins/sessions#create', as: 'admin_session'
    delete 'admins/sign_out' => 'admins/sessions#destroy', as: 'destroy_admin_session'
    get 'admins/sign_up' => 'admins/registrations#new', as: 'new_admin_registration'
    post 'admins/sign_up' => 'admins/registrations#create', as: 'admin_registration'
    get 'admins/password/new' => 'admins/passwords#new', as: 'new_admin_password'
    post 'admins/password' => 'admins/passwords#create', as: 'admin_password'
    get 'admins/password/edit' => 'admins/passwords#edit', as: 'edit_admin_password'
    put 'admins/password' => 'admins/passwords#update', as: ''
  end
  # 共通
  root 'home#top'
  get 'about' => 'home#about', as: 'about'
  get 'signup/select' => 'home#signup_select', as: 'signup_select'
  get 'login/select' => 'home#login_select', as: 'login_select'
  get 'rooms/check' => 'rooms#check', as: 'check'
  resources :inquiries, only: [:create] do
    collection do
      post :confirm
    end
  end
  # get 'inquiries/confirm' => 'home#top', as: '/'
  # 管理者
  namespace :admins do
    resources :rooms, only: [:new, :create, :edit, :update]
    get 'top' => 'home#top', as: 'top'
    resources :children, only: [:index, :show]
    resources :contacts, only: [:new, :create, :index, :show] do
      collection do
        post :confirm
      end
    end
    get 'room_access' => 'children#room_access', as: 'room_access'
    put 'room_access/enter' => 'children#enter', as: 'enter'
    put 'room_access/leave' => 'children#leave', as: 'leave'
    get 'room_access/mail' => 'children#mail', as: 'room_access_children_mail'
    get 'room_access/mail_all' => 'children#mail_all', as: 'room_access_mail_all'
    resources :users, only: [:show, :index, :destroy]
    resources :admins, only: [:show, :edit, :update]
    get '/confirm' => 'admins#confirm', as: 'confirm'
    put '/:id/hide' => 'admins#hide', as: 'hide'
    resources :plans, only: [:show, :index]
    resources :groups
    resources :events
    resources :albums
  end
  # ユーザー
  namespace :users do
    get 'top' => 'home#top', as: 'top'
    resources :children
    # post 'children/new' => 'children#create', as: 'new_child'
    # patch 'users/:id/edit' => 'users#update', as: 'edit_user'
    resources :users
    get '/confirm' => 'users#confirm', as: 'confirm'
    put '/:id/hide' => 'users#hide', as: 'hide'
    resources :contacts, only: [:index, :show] do
      member do
        get :read
      end
    end
    resources :plans, only: [:new, :index, :create, :update]
    resources :events do
      resources :event_attendances
    end
    resources :albums
  end
end

app/views/admins/admins/confirm.html.slim
.container
  - if admin_signed_in? && @admin.id == current_admin.id
  .row.confirm__cont
    h3.text-center 本当に退会しますか？
    p.txt_size_s.text-center
      | 退会すると、会員登録情報や
      br
      | これまでの履歴やユーザー情報が閲覧できなくなります。
      br
      | 退会する場合は、「退会する」をクリックして下さい。
    .form.text-center
      = link_to "退会する", admins_hide_path(current_admin), method: :put, "data-confirm" => "本当に退会しますか？", class: "btn btn-lg btn-danger"
      = link_to "退会しない", admins_admin_path(current_admin), class: "btn btn-lg btn-success confirm__btn"

app/views/admins/admins/edit.html.slim
.container
  .row.page_space
    .form
      h2.form__heading
        | 管理者情報編集
      .form__cont
        = form_for @admin, url: admins_admin_path(@admin.id) do |f|
          = render "layouts/errors", obj: @admin
          .field
            .form__label
              span.form__item 必須
            = f.label :name, class: "form__label"
            = f.text_field :name, autofocus: true, autocomplete: "name", class: "form__item_input",placeholder: "例）横浜学童"
          .field
            .form__label
              span.form__item 必須
            = f.label :email, class: "form__label"
            = f.email_field :email, autofocus: true, autocomplete: "email", class: "form__item_input",placeholder: "例）example@gmail.com"
          .actions
            = f.submit "更新", class: "form__btn"
      .contact__heading
            = link_to '戻る', admins_admin_path(current_admin.id),class:"btn btn_color_gray"

app/views/admins/admins/show.html.slim
.container
  .row
    section
        h2.heading.txt_size_xl
          | 管理者ページ

        .my-page__cont
          h3.marker.txt_size_m
           | ルーム情報
          p
            | 下記ルームキーを会員に伝えることで、このルームに会員を招待することができます。
          .my-page__user_cont
            .my-page__box
                p.my-page__box_heading
                 | ルーム名:
                p.my-page__box_txt
                  = @room.name
            .my-page__box
                p.my-page__box_heading
                  | ルームキー:
                p.my-page__box_txt
                  = @room.key
            = link_to '編集', edit_admins_room_path(@room.id), class:"btn btn_color_orange my-page___btn_position"
        .my-page__cont
          h3.marker.txt_size_m
           | 管理者情報
          .my-page__user_cont
            .my-page__box
                p.my-page__box_heading
                  | 名称:
                p.my-page__box_txt
                  = @admin.name
            .my-page__box
                p.my-page__box_heading
                  | メールアドレス:
                p.my-page__box_txt
                  = @admin.email
            = link_to '編集', edit_admins_admin_path(@admin.id), class:"btn btn_color_orange my-page___btn_position"

          .my-page__cont
            h3.marker.txt_size_m
              = @room.name
              | の会員情報
              | /アルバム
            = link_to admins_users_path, class: "btn btn_color_yellow my-page__btn admin-top__btn2" do
              .txt_color_gray
                | 会員一覧
            = link_to admins_albums_path, class: "btn btn_color_green my-page__btn admin-top__btn2" do
                |アルバムを閲覧する
          .my-page__cont
            h3.marker.txt_size_m
             | 退会・ルームの削除
            = link_to '退会', admins_confirm_path, class: "btn btn_color_red my-page__btn"